version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=vmho-admin
      - GF_SECURITY_ADMIN_PASSWORD=Braekspand01
    user: "1000"
    ports:
      - "80:3000"
    volumes:
      - /home/vmho-admin/vmho-tig-stack/grafana:/var/lib/grafana
