version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=vmho-admin
      - GF_SECURITY_ADMIN_PASSWORD=Braekspand01
    user: "501"
    ports:
      - "3000:3000"
    volumes:
      - /Users/victorkristiansen/Documents/GitHub/vmho-tig-stack/grafana:/var/lib/grafana
