version: "3.7"
services:
  syslog-ng:
    image: balabit/syslog-ng
    container_name: syslog-ng
    ports:
      - "514:514/udp"
    volumes:
      - /home/vmho-admin/vmho-tig-stack/syslog-ng/syslog.conf::/etc/syslog-ng/syslog-ng.confro
